services:
  - type: web
    name: golf-tournament-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: golf-tournament-db
          property: connectionString
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false

databases:
  - name: golf-tournament-db
    databaseName: golf_tournament
    plan: free